### ISSUE TITLE
zh_* l10n v1.3p1

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/translations#11]
From feedbacks in https://groups.google.com/forum/#!topic/i18n-zh/v_qLhCQDg1A:

- [x] Use http://www.ikde.org/discuss/how-to-translate-kde/ as the KDE translation guide.
- [x] Import some discussions over some specific usages of language, e.g. tones, into our guide.

On the [GNOME l10n zh_Hant team](https://l10n.gnome.org/teams/zh_trad/) page I found them using a silghtly modiifed version of zh_CN l10n v1.1, therefore we need to:

- [ ] Amend https://mail.gnome.org/archives/gnome-i18n/2015-September/msg00152.html to form a nice  rationale, possibly translating into zh using MisakaIL-zh +legacyexpr +rime_hant_pinyin.
- [ ] In a polite tone, send the thing to https://groups.google.com/forum/#!forum/chinese-l10n or  zh-l10n@linux.org.tw. These two lists are linked together, and I prefer sending to the latter. In plain text, of course. I should either use MisakaIL-zh +legacyexpr +rime_hant_pinyin or MisakaIL-en@codespeak.

This is part of some thank-you — we've ported (huh) bunches of their translations to zh_CN.

- [ ] Also, I think I should add some examples for those *modern* fonts I talked about. For UI fonts, I expect sans-serifs with straight borders, i.e. 无喇叭口黑体, with other optimizations for reading on-screen.
Source Han Sans, WenQuanYi & Droid Sans Fallback, plus Ubuntu are examples of that.

**Comment by Arthur2e5** [comment]
I will put a copy of that mail to work on on some gist.

**Comment by MingcongBai** [comment]
Cool.

**Comment by Arthur2e5** [comment]
New release: https://groups.google.com/d/msg/i18n-zh/v_qLhCQDg1A/9MXL2WdABQAJ

Let me finish preparing for the history exam first.

**Comment by Arthur2e5** [comment]
Unfortunately I am releasing 1.3p2.

**Comment by Arthur2e5** [comment]
Subject: 由本人維護的自由軟件本地化指南 (zh_CN) 分支

各位 zh_TW 和 zh_HK 的譯者們好，

由於 zh_CN 本地化指南 1.1 年久失修，在一些排版格式的處理上顯得過於老舊甚至於醜陋，本人對其進行了分支，目前版本號更新到了到 1.3-patch2。我注意到 zh_trad 的 GNOME 翻譯頁面上有個指向一份由 zh_CN 1.1 改來的 zh_Hant 版本的鏈接，想著這裡大概也需要就決定發來了。

更新的重點是括弧、空白與省略號為主的標點符號選用。因為找不到 Aron 編輯時的 OpenOffice 3.x ODT 文稿，我在重新製作 ODT 的過程中順便重寫了不少語句，不過考慮到 zh_TW 的用詞和句法習慣大概對你們也沒有什麼區別，畢竟還是都要大改一通。

附件是目前的 1.3p2 版本 PDF 及 ODT；要獲得最新版本的話可以去 https://repo.anthonos.org/misc/l10n 看看。repo.anthonos.org 是[臺灣國立暨南國際](http://www.ncnu.edu.tw)提供的伺服器，在香港和臺灣的訪問速度估計是不會差。

這封郵件用的還是 RIME 的拼音輸入，因為沒有地區用詞轉換所以讀起來可能還是略顯奇怪，還請各位見諒。

[GPGSig][Atts][Attsigs]

这样行吗？？

**Comment by Arthur2e5** [comment]
没有意见的话，我先写化学作业，明天再发。

**Comment by Arthur2e5** [comment]
好好好，今天干。
