### ISSUE TITLE
zh_CN_l10n 1.4

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/translations#13]
- [ ] Import edits found in zh_TW:

  > 1. 遇到說明英文標點的訊息時，除了翻譯為中文外，請在譯文中加入該標點，並在標點前後加上中文 (較建議) 或英文引號。例："seperated by common" 即：以半形冒號「:」隔開；或以半形冒號 \":\" 隔開
  > 2. 遇到說明選單的訊息時，例如：System > Administration ，可以見到頭文字大寫，這麼做除了模擬選單本身頭文字大寫外，還能在同是小寫的句子中吸引讀者的目光。因此請使用上下引號將選目內容括住，以達到同樣效果：「系統」>「管理」，並請注意標點之間無需空格。另一種表示方式為 [系統] > [管理]，括號與 > 之間需添加半形空格隔開，但由於 [] 括號並非規範的中文標點符號，因此此種表達方式較不建議使用。
  >
  > zh_CN:
  >
  > 1. 遇到说明英文标点的消息时，除了翻译为中文外，请在译文中加入该标点，并在标点前后加上弯（GUI）或直（CLI）引号。例如seperated by comma译为“以半角冒号‘:’隔开”[a]，或“以半角冒号 ":" 隔开”。
  > 2. 遇到说明菜单的消息时，例如：System > Administration ，可以见到首字母大写，这样做除了模仿菜单本身首字母大写外，还能在同是小写的句子中吸引读者的目光。因此请使用半角方括号括住，如 [系统] > [管理]，括号与 > 之间需添加半角空格隔开。
  > 
  > a: 这里是因为引号嵌套用了单引号。
- [ ] Mention the *General Punctuation* chart.
- [ ] Link to [v1.1](https://docs.google.com/document/d/1vGzsxjRX7V5XarZdeSWV5Jj5YEbrUECe3zYDwVBVf4o) and [twfork](https://docs.google.com/document/d/1Zs4CS_ZjN-imnImq4aEsiVYih8zkIkVZTSQim13_kYg)

**Comment by Arthur2e5** [comment]
Additionally, mention https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format and consider including this table:

常用日期时间格式对应
----------------------------------

src|dst
---|---
%a|%A
%A, %B %e|%b%e日%A
%a %b %e|%b%e日 (%a)
%A, %B %d|%m月%d日%A
%A, %B %e, %Y|%Y年%b%e日%A
%a, %d %B %Y|%Y年%m月%d日 (%a)
%A, %B %d, %Y|%Y年%m月%d日%A
%d %B %Y|%Y年%m月%d日
%l:%M:%S %p|%p%l∶%M∶%S
%R:%S|%R:%S

**Comment by MingcongBai** [comment]
Very useful.

**Comment by Arthur2e5** [comment]
This should be 1.4 instead……

**Comment by Arthur2e5** [comment]
[zh_CN_l10n_1.4.pdf](https://github.com/AOSC-Dev/translations/files/38032/zh_CN_l10n_1.4.pdf)

**Comment by Arthur2e5** [comment]
@JeffBai 请求评价

**Comment by Arthur2e5** [comment]
Officially released https://repo.aosc.io/misc/l10n/zh_CN_l10n_1.4.pdf.
