### ISSUE TITLE
Import and sort Crowdin stuffs

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/translations#3]
Foo Bar. And don't bring pots in.

**Comment by MingcongBai** [comment]
Requesting a recommended way to organized files from different languages.

**Comment by Arthur2e5** [comment]
Qt ts can either be transliterated to po (with metadata comments?) or use their chain. I think either is acceptable as long as everything is text

**Comment by Arthur2e5** [comment]
I guess most translations in crowdin are outdated now, so not importing any more. Just use it as some backup TM and grab as needed.

**Comment by MingcongBai** [comment]
Very true.
