### ISSUE TITLE
zh_CN l10n Guide 1.3

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/translations#7]
Here are the requirements for v1.3 release:

- [x] Correct language name.
  - 简体中文 -> 大陆简中 OR 中文（中国）
  - Simplified Chinese / Chinese ([Ss]implified) -> Chinese (China) / PRC
- [x] Parentheses: Use the MS Way.
  - No spaces for Hotkey Indicator ASCII PAR.
  - Use CJK PAR for CJK.
  - Use ASCII PAR for Western text, things like `(R)` and code (which should always be as-is).
- [x] Tool: Translate Toolkit.
- [x] Separate chapters for Styling and File Format.

It will be tricky to keep the page count small then.

**Comment by Arthur2e5** [comment]
Polishing.

**Comment by Arthur2e5** [comment]
Done!

**Comment by MingcongBai** [comment]
It would be really awesome if we can use TeX instead... then there is actual point of hosting the document on here.

**Comment by Arthur2e5** [comment]
No, I prefer LibreOffice.

**Comment by MingcongBai** [comment]
Right...
