### ISSUE TITLE
Bash44 translation ready @ upstream

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/translations#9]
https://groups.google.com/forum/#!topic/i18n-zh/2E8tkwLkKqI

**Comment by MingcongBai** [comment]
Good to hear that (I guess?).

**Comment by Arthur2e5** [comment]
Sent to upstream, 1 untranslated.

**Comment by Arthur2e5** [comment]
@JeffBai 我成功强行覆盖成自己的翻译了嘿嘿
